[2024-03-10T05:17:14.904+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.create_db manual__2024-03-10T05:03:21.788121+00:00 [queued]>
[2024-03-10T05:17:14.909+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.create_db manual__2024-03-10T05:03:21.788121+00:00 [queued]>
[2024-03-10T05:17:14.910+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-10T05:17:14.922+0000] {taskinstance.py:2214} INFO - Executing <Task(SqliteOperator): create_db> on 2024-03-10 05:03:21.788121+00:00
[2024-03-10T05:17:14.930+0000] {standard_task_runner.py:60} INFO - Started process 475 to run task
[2024-03-10T05:17:14.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'create_db', 'manual__2024-03-10T05:03:21.788121+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpheyqa5ih']
[2024-03-10T05:17:14.936+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask create_db
[2024-03-10T05:17:14.994+0000] {task_command.py:423} INFO - Running <TaskInstance: podcast_summary.create_db manual__2024-03-10T05:03:21.788121+00:00 [running]> on host f9b25bf10c44
[2024-03-10T05:17:15.088+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='create_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T05:03:21.788121+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T05:03:21.788121+00:00'
[2024-03-10T05:17:15.089+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS episodes (
                link TEXT primary key,
                title TEXT,
                filename TEXT,
                published TEXT,
                description TEXT
            )
        
[2024-03-10T05:17:15.103+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `podcasts` isn't defined
[2024-03-10T05:17:15.106+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=create_db, execution_date=20240310T050321, start_date=20240310T051714, end_date=20240310T051715
[2024-03-10T05:17:15.122+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task create_db (The conn_id `podcasts` isn't defined; 475)
[2024-03-10T05:17:15.147+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-10T05:17:15.179+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SqliteOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
  result = cls.__new__(cls)

[2024-03-10T05:17:15.196+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
