[2024-03-10T05:16:57.600+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: podcast_summary.create_db manual__2024-03-10T05:15:44.060547+00:00 [queued]>
[2024-03-10T05:16:57.608+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: podcast_summary.create_db manual__2024-03-10T05:15:44.060547+00:00 [queued]>
[2024-03-10T05:16:57.608+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-10T05:16:57.621+0000] {taskinstance.py:2214} INFO - Executing <Task(SqliteOperator): create_db> on 2024-03-10 05:15:44.060547+00:00
[2024-03-10T05:16:57.625+0000] {standard_task_runner.py:60} INFO - Started process 473 to run task
[2024-03-10T05:16:57.628+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary', 'create_db', 'manual__2024-03-10T05:15:44.060547+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpawtpoh02']
[2024-03-10T05:16:57.629+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask create_db
[2024-03-10T05:16:57.678+0000] {task_command.py:423} INFO - Running <TaskInstance: podcast_summary.create_db manual__2024-03-10T05:15:44.060547+00:00 [running]> on host f9b25bf10c44
[2024-03-10T05:16:57.841+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='podcast_summary' AIRFLOW_CTX_TASK_ID='create_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T05:15:44.060547+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T05:15:44.060547+00:00'
[2024-03-10T05:16:57.843+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS episodes (
                link TEXT primary key,
                title TEXT,
                filename TEXT,
                published TEXT,
                description TEXT
            )
        
[2024-03-10T05:16:57.881+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `podcasts` isn't defined
[2024-03-10T05:16:57.887+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=podcast_summary, task_id=create_db, execution_date=20240310T051544, start_date=20240310T051657, end_date=20240310T051657
[2024-03-10T05:16:57.913+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task create_db (The conn_id `podcasts` isn't defined; 473)
[2024-03-10T05:16:57.921+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-10T05:16:57.931+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SqliteOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
  result = cls.__new__(cls)

[2024-03-10T05:16:57.944+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
